id: 27cb36b7e78b4be0a325a43420ecd05e
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_312-Entering_the_City_of_Vaisali-v2
  language: bo
  author: ''
  volume: {}
